// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ggcisbssrophlmcrecqh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdnY2lzYnNzcm9waGxtY3JlY3FoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE1MjY4MDEsImV4cCI6MjA2NzEwMjgwMX0.8891At0sXfiB6mZkBgfDniA5NAvp8BogNh9b_f_guks";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});